-- Term schedule v3 - FIRST REAL IMPORT (term 2026-08-10 to 2026-09-23).
-- Wipes ALL business data (system unused before this); keeps users,
-- settings and the real horses. Generated by db/import/gen_005_term_v3.py.

DELETE FROM invoice_lines;
DELETE FROM invoices;
DELETE FROM term_passes;
DELETE FROM reschedule_credits;
DELETE FROM rides;
DELETE FROM recurring_rides;
DELETE FROM contact_horse_prefs;
DELETE FROM contact_availability;
DELETE FROM contacts;
DELETE FROM guides;
DELETE FROM ride_types;
DELETE FROM todos;
DELETE FROM service_contacts;

INSERT INTO ride_types (name, duration_min, price_cents) VALUES ('Therapy session', 45, 0);

-- Staff
INSERT INTO guides (name, is_assistant, notes) VALUES ('Tamara', false, '');
INSERT INTO guides (name, is_assistant, notes) VALUES ('Gisela', false, '');
INSERT INTO guides (name, is_assistant, notes) VALUES ('Naomi', false, '');
INSERT INTO guides (name, is_assistant, notes) VALUES ('Hannah', false, '');
INSERT INTO guides (name, is_assistant, notes) VALUES ('MJ', false, 'Tentative on the Tuesday 15:00 group (bracketed ''?'').');
INSERT INTO guides (name, is_assistant, notes) VALUES ('Elri', true, '');
INSERT INTO guides (name, is_assistant, notes) VALUES ('Therapist (name TBC)', false, 'Runs the therapy sessions. Real name still to be confirmed.');

-- Riders
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Adanna', NULL, 2011, false, '', '', '2 years'' experience. Marked ''?'' in source.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Aeryn', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Aira', 'beginner-intermediate', NULL, true, 'Sharan', 'Gr 3', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Akul', 'beginner', NULL, true, '', '', 'Collected, but no school/grade/teacher recorded.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Alistair', NULL, 2014, false, '', '', '''have ridden'' (prior experience).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Amalia', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Anika', NULL, NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Anna', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Asher', 'intermediate', NULL, false, '', '', 'Marked ''?'' in source.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Ayaan', 'beginner', NULL, true, 'Sue', 'Gr 5', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Azania', 'beginner', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Azara', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Cairo', 'beginner-intermediate', NULL, true, 'Nicole', 'Gr 1', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Charlie', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Chloe', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Dalia', 'beginner', NULL, true, 'Nadia', 'Gr 2', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Elisa', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Eliza', 'beginner', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Elizabeth', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Ella C', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Ella J', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Ella P', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Eloise', NULL, 2019, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Emelie', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Emily M', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Emily P', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Emily S', 'beginner', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Erin G', NULL, 2019, false, '', '', 'Thursday 16:30 with Phoebe.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Erin J', 'intermediate', NULL, false, '', '', 'The Erin in the Philline group.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Everly', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Frankie', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Grace', NULL, NULL, false, '', '', 'Which Grace is unresolved (Monday 16:30 group) - provisional record.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Grace A', 'advanced', NULL, false, '', '', 'Marked ''(2x)'' in source - meaning unclear.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Gwynn', 'beginner', NULL, true, 'Summer', 'K2', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Halo', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Indigo', 'beginner-intermediate', NULL, false, '', '', 'Rides 3x per week (Mon, Tue, Fri).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Isa', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Jo', NULL, 2012, false, '', '', '''have ridden'' (prior experience).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Kaia G', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Kaia J', 'beginner-intermediate', NULL, true, 'Nicole', 'Gr 1', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Kerry', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Ksenija', 'beginner', NULL, false, '', '', 'Explicitly marked beginner.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Lara', 'intermediate', NULL, false, '', '', 'Provisional (bracketed in source).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Layla', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Leah', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Lia', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Lilly A', 'advanced', NULL, false, '', '', 'Possible duplicate of ''Lily A'' (Friday) - verify.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Lily A', 'intermediate', NULL, false, '', '', 'Possible duplicate of ''Lilly A'' (Thursday); marked ''(2x)''.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Maya', 'advanced', NULL, false, '', '', 'Possibly the same person as ''Maya Haley'' (Monday).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Maya Haley', 'intermediate', NULL, false, '', '', 'One student or two (Maya, Haley)? Unresolved.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Meaghan', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Mia', 'intermediate', NULL, false, '', '', 'Provisional (bracketed in source).');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Micaiah', 'beginner', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Morgan', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Nolan', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Norah', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Olivia', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Olympia', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Owen', NULL, NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Paige', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Paizley', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Paula', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Philline', 'intermediate', NULL, false, '', '', 'Marked ''(2x)'' in source - meaning unclear.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Phoebe', NULL, NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Salamander', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Sean', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Shaylah', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Sienna A', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Sienna L', 'intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Sierra', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Sophie', NULL, NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Taheera', 'advanced', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Tilda', 'beginner-intermediate', NULL, false, '', '', 'Marked ''(2x)'' in source - meaning unclear.');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Vicky', 'beginner-intermediate', NULL, false, '', '', '');
INSERT INTO contacts (name, experience, birth_year, needs_collection, collection_teacher, collection_class, notes)
VALUES ('Zara', 'advanced', NULL, false, '', '', '');

-- Weekly templates (44), term-bound 2026-08-10 .. 2026-09-23
WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '12:30', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'MON-01')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Owen']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '13:15', 75, NULL, 'beginner', '2026-08-10', '2026-09-23', 'MON-02')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Azania']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '13:45', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'MON-03: Empty slot - no student named in source.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '14:00', 60, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'MON-04')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Sean']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '14:55', 75, NULL, 'beginner-intermediate', '2026-08-10', '2026-09-23', 'MON-05')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Cairo', 'Vicky']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '15:00', 45, (SELECT id FROM ride_types WHERE name = 'Therapy session'), NULL, '2026-08-10', '2026-09-23', 'MON-06: Therapy session on Tara/Bella.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY['Tara', 'Bella'])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Therapist (name TBC)']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '15:00', 60, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'MON-07')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Leah']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '15:00', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'MON-08')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Anika']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '15:00', 60, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'MON-09: Marked ''?'' in source.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Asher']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '16:00', 60, NULL, 'beginner-intermediate', '2026-08-10', '2026-09-23', 'MON-10: No collection tick in source but school details in Monday header - verify.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Aira']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '16:00', 45, (SELECT id FROM ride_types WHERE name = 'Therapy session'), NULL, '2026-08-10', '2026-09-23', 'MON-11: Therapy session on Tara/Bella.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY['Tara', 'Bella'])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Therapist (name TBC)']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '16:30', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'MON-12')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Paige', 'Aeryn', 'Elizabeth', 'Indigo']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '16:30', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'MON-13: Gisela bracketed in source - likely drop-in support.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Layla', 'Nolan', 'Maya Haley', 'Grace']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (1, '16:00', 105, NULL, 'advanced', '2026-08-10', '2026-09-23', 'MON-14')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Morgan', 'Lia']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '13:30', 60, NULL, 'beginner', '2026-08-10', '2026-09-23', 'TUE-01')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Emily S']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '15:00', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'TUE-02')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Ella C', 'Chloe']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '15:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'TUE-03: MJ tentative (white heart bracketed ''?'').')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Olivia', 'Kaia J', 'Gwynn', 'Indigo', 'Eloise']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Hannah', 'Naomi', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '16:00', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'TUE-04')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Kerry', 'Kaia G']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '16:15', 60, NULL, 'beginner-intermediate', '2026-08-10', '2026-09-23', 'TUE-05')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Aira']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '16:30', 75, NULL, 'beginner-intermediate', '2026-08-10', '2026-09-23', 'TUE-06')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Isa', 'Ella J', 'Charlie']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (2, '16:15', 105, NULL, 'advanced', '2026-08-10', '2026-09-23', 'TUE-07')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Emelie', 'Taheera', 'Ella P']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (3, '14:45', 45, (SELECT id FROM ride_types WHERE name = 'Therapy session'), NULL, '2026-08-10', '2026-09-23', 'WED-01: Therapy session on Peaches.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY['Peaches'])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Therapist (name TBC)']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (3, '15:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'WED-02')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Frankie', 'Sierra', 'Paizley', 'Micaiah', 'Eliza']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Gisela', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (3, '16:30', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'WED-03: (Lara + Mia) bracketed in source - provisional pairing.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Lara', 'Mia', 'Layla', 'Nolan', 'Norah']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (3, '16:15', 105, NULL, 'advanced', '2026-08-10', '2026-09-23', 'WED-04')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Salamander', 'Halo']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (3, '16:30', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'WED-05')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Elisa', 'Amalia', 'Paula']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '13:00', 75, NULL, 'advanced', '2026-08-10', '2026-09-23', 'THU-01: (+Lilly) bracketed - tentative.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Maya', 'Zara', 'Lilly A']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '13:45', 60, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'THU-02')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Sean']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '13:30', 75, NULL, 'beginner-intermediate', '2026-08-10', '2026-09-23', 'THU-03')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Shaylah', 'Olympia', 'Tilda']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '15:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'THU-04: All four riders are school collections.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Dalia', 'Aira', 'Ayaan', 'Akul']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela', 'Tamara', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '15:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'THU-05')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Jo', 'Alistair']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '16:30', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'THU-06')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Phoebe', 'Erin G']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Hannah']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '16:30', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'THU-07')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Philline', 'Erin J', 'Sienna L']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (4, '16:30', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'THU-08')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Everly', 'Emily P']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '12:30', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-01')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Sophie']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '14:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-02: Empty slot - being re-filled (was Kate/Matilda/Sebastian).')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '14:00', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-03')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Meaghan', 'Indigo', 'Ksenija']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara', 'Elri']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '14:00', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-04: Empty slot - v1 had Grace K here, likely still her.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '15:30', 60, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-05: Marked ''?'' in source.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Adanna']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '15:15', 60, NULL, 'advanced', '2026-08-10', '2026-09-23', 'FRI-06')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Azara']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '15:15', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'FRI-07')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Sienna A', 'Emily M']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '16:30', 75, NULL, 'intermediate', '2026-08-10', '2026-09-23', 'FRI-08')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Leah', 'Anna', 'Lily A']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Tamara']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '16:30', 75, NULL, NULL, '2026-08-10', '2026-09-23', 'FRI-09: Empty slot - no student named in source.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY[]::text[]) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Naomi']);

WITH t AS (
    INSERT INTO recurring_rides (weekday, start_time, duration_min, ride_type_id, level, start_date, end_date, notes)
    VALUES (5, '16:30', 90, NULL, 'advanced', '2026-08-10', '2026-09-23', 'FRI-10: ''(Ice)'' in source - likely the horse.')
    RETURNING id
), p AS (
    INSERT INTO recurring_participants (recurring_id, contact_id, frequency)
    SELECT t.id, c.id, 'weekly' FROM t, contacts c
     WHERE c.name = ANY(ARRAY['Lia', 'Grace A']) AND NOT c.archived
    RETURNING 1
), ph AS (
    INSERT INTO recurring_participants (recurring_id, horse_id, frequency)
    SELECT t.id, h.id, 'weekly' FROM t, horses h WHERE h.name = ANY(ARRAY[]::text[])
    RETURNING 1
)
INSERT INTO recurring_guides (recurring_id, guide_id, mode)
SELECT t.id, g.id, 'foot' FROM t, guides g WHERE g.name = ANY(ARRAY['Gisela']);

